<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key' => 'group_605dd1a8c1044',
		'title' => 'General Options',
		'fields' => array(
			array(
				'key' => 'field_605de5ea80251',
				'label' => 'Access',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_605de62880253',
				'label' => 'Domain Whitelist',
				'name' => 'domain_whitelist',
				'type' => 'textarea',
				'instructions' => 'one domain per line',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_605de5fe80252',
				'label' => 'Email Whitelist',
				'name' => 'email_whitelist',
				'type' => 'textarea',
				'instructions' => 'one email per line',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6078ce2928b4c',
				'label' => 'Defaults',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6238c64170fcd',
				'label' => 'Starting Quote Number',
				'name' => 'starting_quote_number',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6078d02332505',
				'label' => 'Hourly Rate',
				'name' => 'hourly_rate',
				'type' => 'number',
				'instructions' => 'Your base labor cost per hour. Both pricing modes start here before adding material, break-in, and margin.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6817a0013a101',
				'label' => 'Pricing Mode',
				'name' => 'default_pricing_mode',
				'type' => 'radio',
				'instructions' => 'Choose how new leads should calculate pricing by default. Utilization adjusts labor rate based on available capacity. Cost Plus starts from labor and material cost, then adds markup.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'utilization' => 'Utilization',
					'cost_plus' => 'Cost Plus',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'utilization',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_6078ce3628b4d',
				'label' => 'Margin',
				'name' => 'default_margin',
				'type' => 'number',
				'instructions' => 'Your default markup percentage. In Cost Plus, this is applied directly to total unit cost. In Utilization, it also influences the hourly labor rate that feeds the final price.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6078ce6128b4e',
				'label' => 'EFF',
				'name' => 'default_eff',
				'type' => 'number',
				'instructions' => 'Expected production efficiency as a percent. Lower efficiency raises labor cost because the same work takes more time.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6078ce8328b4f',
				'label' => '# People',
				'name' => 'default_people',
				'type' => 'number',
				'instructions' => 'How many people are assumed to run the job. More people increase labor cost in both pricing modes.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6078ceab31f6f',
				'label' => 'EAU',
				'name' => 'default_eau',
				'type' => 'number',
				'instructions' => 'Expected annual usage. Use this as your default planning volume for new parts when you want pricing to start from a typical yearly demand assumption.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6078cebb31f70',
				'label' => '# of Shifts',
				'name' => 'default_shift',
				'type' => 'number',
				'instructions' => 'How many shifts are assumed to support the work. In Utilization pricing, this affects available yearly capacity and therefore the utilization-based labor rate.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_61d7384412908',
				'label' => 'Break In',
				'name' => 'default_break_in',
				'type' => 'number',
				'instructions' => 'One-time setup or startup cost. It is spread across the quoted quantity, so lower quantities absorb more of this cost per unit.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_627aa4e7ee873',
				'label' => 'Metal Adder',
				'name' => 'default_metal_adder',
				'type' => 'number',
				'instructions' => 'Default metal factor added into new pricing inputs when a part needs metal-related cost adjustment. This contributes through the part pricing input rather than replacing material cost.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6818b1012f201',
				'label' => 'Integrations',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6818b11f2f202',
				'label' => 'Enabled Integrations',
				'name' => 'enabled_integrations',
				'type' => 'checkbox',
				'instructions' => 'Choose which integrations this client site should have available.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'nutshell' => 'Nutshell',
				),
				'allow_custom' => 0,
				'default_value' => array(),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_6818b1492f203',
				'label' => 'Nutshell Account Name',
				'name' => 'nutshell_account_name',
				'type' => 'text',
				'instructions' => 'Optional label for the connected Nutshell workspace or team account.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6818b15f2f204',
				'label' => 'Nutshell API User',
				'name' => 'nutshell_api_user',
				'type' => 'text',
				'instructions' => 'The Nutshell API username or email for this workspace.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6818b1762f205',
				'label' => 'Nutshell API Key',
				'name' => 'nutshell_api_key',
				'type' => 'text',
				'instructions' => 'The API key used to create contacts, accounts, and leads in Nutshell.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62c465069baa5',
				'label' => 'Quotes',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62c4650e9baa6',
				'label' => 'Quote Expires After',
				'name' => 'quote_expires_after',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'days',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_62c4660a9baa7',
				'label' => 'Follow Up After',
				'name' => 'follow_up_after',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => 'days',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

endif;
