<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key' => 'group_6040e9eaa80cb',
		'title' => 'Lead Data',
		'fields' => array(
			array(
				'key' => 'field_605dd637634c1',
				'label' => 'Contact',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_610ab8741f527',
				'label' => 'Customer',
				'name' => 'customer',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'customer',
				),
				'taxonomy' => '',
				'allow_null' => 1,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array(
				'key' => 'field_6040e9f2f48c0',
				'label' => 'First Name',
				'name' => 'first_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6040e9faf48c1',
				'label' => 'Last Name',
				'name' => 'last_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6040ea01f48c2',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6040ea08f48c3',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6040ea0ef48c4',
				'label' => 'Company',
				'name' => 'company',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61151dc684830',
				'label' => 'Certification',
				'name' => 'certification',
				'type' => 'true_false',
				'instructions' => 'Include certification',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
			array(
				'key' => 'field_65b8fb21d48c3',
				'label' => 'Metal Factor',
				'name' => 'include_metal_factor',
				'type' => 'true_false',
				'instructions' => 'Include metal factor breakdown',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => 'Yes',
				'ui_off_text' => 'No',
			),
			array(
				'key' => 'field_605dd5f8634c0',
				'label' => 'Details',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6040eab1f48c7',
				'label' => 'Service',
				'name' => 'service',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'#Metal Preparation & Improvement' => '#Metal Preparation & Improvement',
					'Abrasive Blast Options' => 'Abrasive Blast Options',
					'Vibratory Deburring' => 'Vibratory Deburring',
					'Shot Peening Services' => 'Shot Peening Services',
					'Steel Shot Blasting Service' => 'Steel Shot Blasting Service',
					'Immersion Washing' => 'Immersion Washing',
					'Mass Finishing' => 'Mass Finishing',
					'Parts Cleaning' => 'Parts Cleaning',
					'Vacuum Impregnation Services' => 'Vacuum Impregnation Services',
					'#Plating' => '#Plating',
					'Coating' => 'Coating',
					'#Labratory Testing' => '#Labratory Testing',
					'Bend Testing' => 'Bend Testing',
					'Heat Testing' => 'Heat Testing',
					'Cross Sectioning' => 'Cross Sectioning',
					'#Consulting' => '#Consulting',
					'Prototyping' => 'Prototyping',
					'Process Development' => 'Process Development',
				),
				'default_value' => false,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6040ebbe8476a',
				'label' => 'Industry',
				'name' => 'industry',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Aerospace' => 'Aerospace',
					'Automotive' => 'Automotive',
					'Military & Defense' => 'Military & Defense',
					'Electronics' => 'Electronics',
					'Firearms' => 'Firearms',
					'Fasteners' => 'Fasteners',
					'Medical' => 'Medical',
					'Oil & Gas' => 'Oil & Gas',
					'Optics' => 'Optics',
					'Power Generation' => 'Power Generation',
					'Semiconductors' => 'Semiconductors',
					'Tool & Die' => 'Tool & Die',
					'Hardware' => 'Hardware',
					'Personal Firearm' => 'Personal Firearm',
					'Jewelry' => 'Jewelry',
				),
				'default_value' => false,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6040ec36ef967',
				'label' => 'Business',
				'name' => 'business',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'I am a business' => 'I am a business',
					'I am not a business' => 'I am not a business',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_6040ec54ef968',
				'label' => 'Finishing Type',
				'name' => 'finishing_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Functional Finishing' => 'Functional Finishing',
					'Cosmetic Finishing' => 'Cosmetic Finishing',
				),
				'default_value' => false,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6040ec79ef969',
				'label' => 'Stage',
				'name' => 'stage',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Ready to buy' => 'Ready to buy',
					'Need a formal quote' => 'Need a formal quote',
					'Need a rough estimate' => 'Need a rough estimate',
				),
				'default_value' => false,
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6040eca0ef96a',
				'label' => 'Notes',
				'name' => 'notes',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_605dd64f634c2',
				'label' => 'Spec Data',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6192c98d293ba',
				'label' => 'Part Data',
				'name' => 'part_data',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_6192c9b3293bb',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Part',
				'sub_fields' => array(
					array(
						'key' => 'field_62d6dfa8a2273',
						'label' => 'Part Lookup',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Part not found.',
						'new_lines' => '',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_621d0f3b9bdec',
						'label' => 'Upload Part File',
						'name' => '',
						'type' => 'message',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'message' => 'Caution: This will override the current file data.
<div class="js-upload-part-file-wrapper"></div>',
						'new_lines' => '',
						'esc_html' => 0,
					),
					array(
						'key' => 'field_6192c9b3293bb',
						'label' => 'File Name',
						'name' => 'file_name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6192c9c5293bc',
						'label' => 'Surface Area',
						'name' => 'area_computed',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ft²&nbsp;&nbsp;<i class="fas fa-info-circle" data-toggle="tooltip" data-title="Override this value on the overrides tab"></i>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_656f4d76a6402',
						'label' => 'Surface Area Override',
						'name' => 'area_override',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => 'no-label',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'ft²',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_6192c9e4293bd',
						'label' => 'Volume',
						'name' => 'volume_computed',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in³&nbsp;&nbsp;<i class="fas fa-info-circle" data-toggle="tooltip" data-title="Override this value on the overrides tab"></i>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_65b904a06d111',
						'label' => 'Volume Override',
						'name' => 'volume_override',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in³',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_6193eada83418',
						'label' => 'dX',
						'name' => 'd_x_computed',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in&nbsp;&nbsp;<i class="fas fa-info-circle" data-toggle="tooltip" data-title="Override this value on the overrides tab"></i>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_6193eaf483419',
						'label' => 'dY',
						'name' => 'd_y_computed',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in&nbsp;&nbsp;<i class="fas fa-info-circle" data-toggle="tooltip" data-title="Override this value on the overrides tab"></i>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_6193eafd8341a',
						'label' => 'dZ',
						'name' => 'd_z_computed',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in&nbsp;&nbsp;<i class="fas fa-info-circle" data-toggle="tooltip" data-title="Override this value on the overrides tab"></i>',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_65b907e7e1e46',
						'label' => 'dX Override',
						'name' => 'd_x_override',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_65b907e7e1e47',
						'label' => 'dY Override',
						'name' => 'd_y_override',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_65b907e7e1e48',
						'label' => 'dZ Override',
						'name' => 'd_z_override',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.33333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'in',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array(
						'key' => 'field_6192c9ef293be',
						'label' => 'Base Metal',
						'name' => 'base_metal',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Stainless Steel (300/400 Series)' => 'Stainless Steel (300/400 Series)',
							'ABS (PLASTIC)' => 'ABS (PLASTIC)',
							'ABS/PC (PLASTIC)' => 'ABS/PC (PLASTIC)',
							'ALBEMET' => 'ALBEMET',
							'Aluminum-Silicon (AlSi10Mg)' => 'Aluminum-Silicon (AlSi10Mg)',
							'Alumina (Ceramic)' => 'Alumina (Ceramic)',
							'Aluminum Alloys (1000, 3000, 4000, 5000,,6000)' => 'Aluminum Alloys (1000, 3000, 4000, 5000,,6000)',
							'Aluminum Alloys (2000, 7000)' => 'Aluminum Alloys (2000, 7000)',
							'Aluminum (Cast)' => 'Aluminum (Cast)',
							'Alloy 41 (NiCrCoMo)' => 'Alloy 41 (NiCrCoMo)',
							'Alloy 52 (NiFe)' => 'Alloy 52 (NiFe)',
							'Beryllium-Copper' => 'Beryllium-Copper',
							'Borosilicate Glass' => 'Borosilicate Glass',
							'Brass/Bronze' => 'Brass/Bronze',
							'Brass/Bronze (Leaded)' => 'Brass/Bronze (Leaded)',
							'Carbon/Graphite-Epoxy Composite' => 'Carbon/Graphite-Epoxy Composite',
							'Copper' => 'Copper',
							'Copper-Molybdenum 25/75' => 'Copper-Molybdenum 25/75',
							'Copper-Tungsten 25/75' => 'Copper-Tungsten 25/75',
							'FEP (PLASTIC)' => 'FEP (PLASTIC)',
							'INVAR-36 (NICKEL-IRON ALLOY)' => 'INVAR-36 (NICKEL-IRON ALLOY)',
							'Carbon & Low Alloy Steel' => 'Carbon & Low Alloy Steel',
							'Powdered Metal (Steel)' => 'Powdered Metal (Steel)',
							'Steel (Leaded)' => 'Steel (Leaded)',
							'Alloy Steel (Cr > 1.5%)' => 'Alloy Steel (Cr > 1.5%)',
							'Kovar (NI-CO-FE ALLOY)' => 'Kovar (NI-CO-FE ALLOY)',
							'L605 Co-Cr-W-Ni Alloy' => 'L605 Co-Cr-W-Ni Alloy',
							'Lead' => 'Lead',
							'Liquid Crystal Polymer (LCP) 30% GLASS FILLED' => 'Liquid Crystal Polymer (LCP) 30% GLASS FILLED',
							'Magnesium Alloys' => 'Magnesium Alloys',
							'Magnesium Silicate (Forsterite: Mg2SiO4)' => 'Magnesium Silicate (Forsterite: Mg2SiO4)',
							'Molybdenum' => 'Molybdenum',
							'Monel (NICKEL-COPPER ALLOY)' => 'Monel (NICKEL-COPPER ALLOY)',
							'Neodymium' => 'Neodymium',
							'Nichrome 80 (ALLOY 650)' => 'Nichrome 80 (ALLOY 650)',
							'Nickel' => 'Nickel',
							'Niobium' => 'Niobium',
							'Nylon (Polyamide)' => 'Nylon (Polyamide)',
							'Nylon (Polyamide Glass-Filled)' => 'Nylon (Polyamide Glass-Filled)',
							'Polyacetal (POM)' => 'Polyacetal (POM)',
							'Polybutylene Terephthalate (PBT)' => 'Polybutylene Terephthalate (PBT)',
							'Polybenzimidazole (PBI)' => 'Polybenzimidazole (PBI)',
							'Polycarbonate' => 'Polycarbonate',
							'Palladium' => 'Palladium',
							'Polyether Ether Ketone (PEEK)' => 'Polyether Ether Ketone (PEEK)',
							'Polyetherimide (PEI-Ultem)' => 'Polyetherimide (PEI-Ultem)',
							'Poly(methyl methacrylate) PMMA' => 'Poly(methyl methacrylate) PMMA',
							'Polymethylpentene (PMP, aka TPX)' => 'Polymethylpentene (PMP, aka TPX)',
							'Polyphenylene Sulfide (Ryton R4 - 40% Fiberglass Filled)' => 'Polyphenylene Sulfide (Ryton R4 - 40% Fiberglass Filled)',
							'Polypropylene (PP)' => 'Polypropylene (PP)',
							'Polystyrene (PS)' => 'Polystyrene (PS)',
							'Polyvinyl Chloride (PVC)' => 'Polyvinyl Chloride (PVC)',
							'Platinum' => 'Platinum',
							'PZT-CERAMIC' => 'PZT-CERAMIC',
							'Silver' => 'Silver',
							'Silicon' => 'Silicon',
							'Silicon-Carbide' => 'Silicon-Carbide',
							'Tin' => 'Tin',
							'Titanium (Commercially Pure)' => 'Titanium (Commercially Pure)',
							'Titanium (Alloy)' => 'Titanium (Alloy)',
							'Tungsten' => 'Tungsten',
							'TZM Molybdenum' => 'TZM Molybdenum',
							'Zinc-Diecast' => 'Zinc-Diecast',
							'VIBRATORY BOWL FINISH' => 'VIBRATORY BOWL FINISH',
							'Urethane-Acrylate Blends' => 'Urethane-Acrylate Blends',
							'Vermiculite' => 'Vermiculite',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6192ce1a293bf',
						'label' => 'Drawing Number',
						'name' => 'drawing_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6192ce28293c0',
						'label' => 'Revision Number',
						'name' => 'revision_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6192ce35293c1',
						'label' => 'Part Number',
						'name' => 'part_number',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333333333',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6192cf3a293cb',
						'label' => 'Processes',
						'name' => 'processes',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_6192cf5d293cc',
						'min' => 0,
						'max' => 0,
						'layout' => 'block',
						'button_label' => 'Add Process',
						'sub_fields' => array(
							array(
								'key' => 'field_6192cf5d293cc',
								'label' => 'Metal',
								'name' => 'metal',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '40',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'ABRASIVE BLAST (STEEL MEDIA)' => 'ABRASIVE BLAST (STEEL MEDIA)',
									'BAKING' => 'BAKING',
									'TUMBLE BLASTING (STEEL SHOT)' => 'TUMBLE BLASTING (STEEL SHOT)',
									'CHEM FILM' => 'CHEM FILM',
									'CHROME' => 'CHROME',
									'COPPER (NEUTRAL-BARREL)' => 'COPPER (NEUTRAL-BARREL)',
									'COPPER (NEUTRAL)' => 'COPPER (NEUTRAL)',
									'COPPER (ACID)' => 'COPPER (ACID)',
									'COPPER (ACID-BARREL)' => 'COPPER (ACID-BARREL)',
									'COPPER (ALKALINE-BARREL)' => 'COPPER (ALKALINE-BARREL)',
									'COPPER (ALKALINE)' => 'COPPER (ALKALINE)',
									'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
									'ELECTROLESS NICKEL (< 1% B)' => 'ELECTROLESS NICKEL (< 1% B)',
									'ELECTROLESS NICKEL (1-4% P)' => 'ELECTROLESS NICKEL (1-4% P)',
									'ELECTROLESS NICKEL (5-9% P)' => 'ELECTROLESS NICKEL (5-9% P)',
									'ELECTROLESS NICKEL (11-13% P)' => 'ELECTROLESS NICKEL (11-13% P)',
									'ELECTROLESS NICKEL-PTFE' => 'ELECTROLESS NICKEL-PTFE',
									'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
									'GOLD (99.7% + AU; HKN 130-200)' => 'GOLD (99.7% + AU; HKN 130-200)',
									'GOLD (99.9% + AU; HKN 130-200)' => 'GOLD (99.9% + AU; HKN 130-200)',
									'GOLD (99.9% + AU; HKN 90 MAX)' => 'GOLD (99.9% + AU; HKN 90 MAX)',
									'GOLD (99.7% + AU; HKN 200+)' => 'GOLD (99.7% + AU; HKN 200+)',
									'GOLD (99.9% + AU; HKN 91-129)' => 'GOLD (99.9% + AU; HKN 91-129)',
									'IMMERSION GOLD' => 'IMMERSION GOLD',
									'IMMERSION TIN' => 'IMMERSION TIN',
									'IMPREG' => 'IMPREG',
									'MASKING' => 'MASKING',
									'NICKEL-SULFAMATE' => 'NICKEL-SULFAMATE',
									'NICKEL-SULFAMATE (BARREL)' => 'NICKEL-SULFAMATE (BARREL)',
									'NICKEL-WOODS STRIKE' => 'NICKEL-WOODS STRIKE',
									'PALLADIUM' => 'PALLADIUM',
									'PALLADIUM-NICKEL (80PD-20NI)' => 'PALLADIUM-NICKEL (80PD-20NI)',
									'PLATINUM' => 'PLATINUM',
									'RHODIUM' => 'RHODIUM',
									'RUTHENIUM' => 'RUTHENIUM',
									'SILVER (BRIGHT)' => 'SILVER (BRIGHT)',
									'SILVER-BARREL (BRIGHT)' => 'SILVER-BARREL (BRIGHT)',
									'SILVER (MATTE)' => 'SILVER (MATTE)',
									'SILVER-BARREL (MATTE)' => 'SILVER-BARREL (MATTE)',
									'SILVER (SEMI-BRIGHT)' => 'SILVER (SEMI-BRIGHT)',
									'SILVER-BARREL (SEMI-BRIGHT)' => 'SILVER-BARREL (SEMI-BRIGHT)',
									'SILVER ANTI-TARNISH INHIBITOR' => 'SILVER ANTI-TARNISH INHIBITOR',
									'TIN (BRIGHT)' => 'TIN (BRIGHT)',
									'TIN (BRIGHT-BARREL)' => 'TIN (BRIGHT-BARREL)',
									'TIN (MATTE)' => 'TIN (MATTE)',
									'TIN (MATTE-BARREL)' => 'TIN (MATTE-BARREL)',
									'TIN-NICKEL-BARREL (65/35)' => 'TIN-NICKEL-BARREL (65/35)',
									'ZINC' => 'ZINC',
									'ZINC-NICKEL' => 'ZINC-NICKEL',
									'VIRATORY FINISH' => 'VIRATORY FINISH',
									'ULTRASONIC WASH' => 'ULTRASONIC WASH',
								),
								'default_value' => false,
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_621d05885eb9e',
								'label' => 'Specification',
								'name' => 'specification',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '60',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_61955b1f0e88f',
								'label' => 'Min Thickness (µin)',
								'name' => 'min_thickness',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6192cf68293cd',
								'label' => 'Max Thickness (µin)',
								'name' => 'max_thickness',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_621fba2f415f4',
								'label' => 'Unit',
								'name' => 'unit',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Standard' => 'Standard',
									'Metric' => 'Metric',
								),
								'default_value' => 'Standard',
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
							array(
								'key' => 'field_6192cf73293ce',
								'label' => 'Time',
								'name' => 'time',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '25',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_6192ceff293c8',
						'label' => 'Plating Line',
						'name' => 'plating_line',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'5 GALLON TANK' => '5 GALLON TANK',
							'2 X 5 GALLON TANK ' => '2 X 5 GALLON TANK ',
							'3 X 5 GALLON TANK' => '3 X 5 GALLON TANK',
							'4 X 5 GALLON TANK' => '4 X 5 GALLON TANK',
							'2.5 GALLON BEAKER' => '2.5 GALLON BEAKER',
							'2X 2.5 GALLON BEAKER' => '2X 2.5 GALLON BEAKER',
							'LAB' => 'LAB',
							'LARGE VIBE BOWL' => 'LARGE VIBE BOWL',
							'LINE 10 BR TIN' => 'LINE 10 BR TIN',
							'LINE 15 MINI HL' => 'LINE 15 MINI HL',
							'LINE 15 MINI HL TIN' => 'LINE 15 MINI HL TIN',
							'LINE 15 MINI HL ZN' => 'LINE 15 MINI HL ZN',
							'LINE 15 MINI HL ZN-NI' => 'LINE 15 MINI HL ZN-NI',
							'LINE 17 EN 1X' => 'LINE 17 EN 1X',
							'LINE 17 EN 2X' => 'LINE 17 EN 2X',
							'LINE 17 EN 3X' => 'LINE 17 EN 3X',
							'LINE 2 ZINC' => 'LINE 2 ZINC',
							'ULTRASONIC WASHER' => 'ULTRASONIC WASHER',
							'VACUUM IMPREG' => 'VACUUM IMPREG',
							'ID TUBE' => 'ID TUBE',
							'TI-PT LINE' => 'TI-PT LINE',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6192cf0d293c9',
						'label' => 'Plating Method',
						'name' => 'plating_method',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Barrel' => 'Barrel',
							'Rack' => 'Rack',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6192cf16293ca',
						'label' => 'Plating Tool',
						'name' => 'plating_tool_barrel',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6192cf0d293c9',
									'operator' => '==',
									'value' => 'Barrel',
								),
							),
						),
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'39"' => '39"',
							'B' => 'B',
							'Jewelers' => 'Jewelers',
							'Micro' => 'Micro',
							'Micro-8512' => 'Micro-8512',
							'S PPB 44' => 'S PPB 44',
							'S PBB 66' => 'S PBB 66',
							'Tandem B' => 'Tandem B',
							'V100 90MM' => 'V100 90MM',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6192d2e1b5cbe',
						'label' => 'Plating Tool',
						'name' => 'plating_tool_rack',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_6192cf0d293c9',
									'operator' => '==',
									'value' => 'Rack',
								),
							),
						),
						'wrapper' => array(
							'width' => '33.333333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'10 CU.FT. BASKET' => '10 CU.FT. BASKET',
							'CHEM FILM' => 'CHEM FILM',
							'EN TANK SPECIAL' => 'EN TANK SPECIAL',
							'Flat Large Hook' => 'Flat Large Hook',
							'Ideal Rack' => 'Ideal Rack',
							'Ideal Rack Double Sided' => 'Ideal Rack Double Sided',
							'LAB WIRE' => 'LAB WIRE',
							'Large Pincher Tine' => 'Large Pincher Tine',
							'Medico Bullet' => 'Medico Bullet',
							'Mini Pincher Tine' => 'Mini Pincher Tine',
							'Pin Rack' => 'Pin Rack',
							'S&Z Rack' => 'S&Z Rack',
							'Small U-Hook' => 'Small U-Hook',
							'SS Flat Tipped Pincher Tine' => 'SS Flat Tipped Pincher Tine',
							'Stick Pincher Tine' => 'Stick Pincher Tine',
							'THERMOCOUPLE RACK' => 'THERMOCOUPLE RACK',
							'ID TUBE PLATING' => 'ID TUBE PLATING',
							'ULTRASONIC WASH TRAY' => 'ULTRASONIC WASH TRAY',
							'PT PLATING LINE RACK' => 'PT PLATING LINE RACK',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_610aba8538ae4',
						'label' => 'Routing',
						'name' => 'routing',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => 'field_610aba9238ae5',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Add Step',
						'sub_fields' => array(
							array(
								'key' => 'field_610aba9238ae5',
								'label' => 'Operation',
								'name' => 'operation',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'LARGE VIBE BOWLS' => 'LARGE VIBE BOWLS',
									'PLASTIC PREP' => 'PLASTIC PREP',
									'ACID COPPER' => 'ACID COPPER',
									'NEUTRAL COPPER PLATE' => 'NEUTRAL COPPER PLATE',
									'ADHESION TEST' => 'ADHESION TEST',
									'AL OX BLAST' => 'AL OX BLAST',
									'ANODIZE' => 'ANODIZE',
									'BAKE (HYDROGEN/STRESS R)' => 'BAKE (HYDROGEN/STRESS R)',
									'TUMBLE BLAST' => 'TUMBLE BLAST',
									'CABINET BLAST' => 'CABINET BLAST',
									'NICKEL-STRIKE-WOODS' => 'NICKEL-STRIKE-WOODS',
									'NICKEL-SULFAMATE' => 'NICKEL-SULFAMATE',
									'COPPER, BRASS, OR BRONZE (NOT LEADED)' => 'COPPER, BRASS, OR BRONZE (NOT LEADED)',
									'COPPER, BRASS, OR BRONZE (LEADED)' => 'COPPER, BRASS, OR BRONZE (LEADED)',
									'BURNISH' => 'BURNISH',
									'CATALYST & ACCELERATOR' => 'CATALYST & ACCELERATOR',
									'CHEM FILM' => 'CHEM FILM',
									'CHROME' => 'CHROME',
									'COPPER-CN' => 'COPPER-CN',
									'HOT DI H20 RINSE' => 'HOT DI H20 RINSE',
									'RT DI H20 RINSE' => 'RT DI H20 RINSE',
									'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
									'EBONOL C' => 'EBONOL C',
									'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
									'ELECTROLESS NICKEL-BORON' => 'ELECTROLESS NICKEL-BORON',
									'EN PLASTIC STRIKE' => 'EN PLASTIC STRIKE',
									'EN-HP' => 'EN-HP',
									'EN-MP ' => 'EN-MP ',
									'EN-LP ' => 'EN-LP ',
									'FERROUSALLOY' => 'FERROUSALLOY',
									'1000, 3000, 4000, and 6000 Series Alloys AL PREP' => '1000, 3000, 4000, and 6000 Series Alloys AL PREP',
									'2000 & 7000 Series Alloys AL PREP' => '2000 & 7000 Series Alloys AL PREP',
									'GLASS BEAD BLAST' => 'GLASS BEAD BLAST',
									'GOLD PLATE (99.9% MIN AU; HKN 90 MAX)' => 'GOLD PLATE (99.9% MIN AU; HKN 90 MAX)',
									'GOLD PLATE (99.9% MIN AU; HKN 130-200)' => 'GOLD PLATE (99.9% MIN AU; HKN 130-200)',
									'GOLD PLATE (99.9% MIN AU; HKN 90-129)' => 'GOLD PLATE (99.9% MIN AU; HKN 90-129)',
									'GOLD PLATE (99.7% MIN AU; HKN 130-170)' => 'GOLD PLATE (99.7% MIN AU; HKN 130-170)',
									'GOLD STRIKE (BARREL)' => 'GOLD STRIKE (BARREL)',
									'GOLD STRIKE (RACK)' => 'GOLD STRIKE (RACK)',
									'IM GOLD' => 'IM GOLD',
									'IM TIN' => 'IM TIN',
									'VACUUM IMPREG 1X' => 'VACUUM IMPREG 1X',
									'VACUUM IMPREG 2X' => 'VACUUM IMPREG 2X',
									'IPA ULTRASONIC CLEAN' => 'IPA ULTRASONIC CLEAN',
									'LOADING' => 'LOADING',
									'MAG PREP' => 'MAG PREP',
									'MAG-EN' => 'MAG-EN',
									'MASKING' => 'MASKING',
									'BRIGHT TIN' => 'BRIGHT TIN',
									'MATTE TIN' => 'MATTE TIN',
									'MG-PREP-CAST' => 'MG-PREP-CAST',
									'TUNGSTEN PREP' => 'TUNGSTEN PREP',
									'MOLY PREP' => 'MOLY PREP',
									'NUETRAL CU' => 'NUETRAL CU',
									'PACK&SHIP' => 'PACK&SHIP',
									'PALLADIUM' => 'PALLADIUM',
									'TUMBLE SHOT BLAST' => 'TUMBLE SHOT BLAST',
									'PALLADIUM-NICKEL ALLOY' => 'PALLADIUM-NICKEL ALLOY',
									'PLATINUM' => 'PLATINUM',
									'PZT CERAMIC' => 'PZT CERAMIC',
									'RACKING' => 'RACKING',
									'RHODIUM' => 'RHODIUM',
									'RUTHENIUM' => 'RUTHENIUM',
									'SILVER PLATE' => 'SILVER PLATE',
									'SILVER STRIKE (RACK)' => 'SILVER STRIKE (RACK)',
									'TARNIBAN KS II -- IMMERSION' => 'TARNIBAN KS II -- IMMERSION',
									'TARNIBAN KS II -- ANODIC' => 'TARNIBAN KS II -- ANODIC',
									'TITANIUM PREP' => 'TITANIUM PREP',
								),
								'default_value' => false,
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 1,
								'ajax' => 0,
								'return_format' => 'value',
								'placeholder' => '',
							),
							array(
								'key' => 'field_6241e2953df4a',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => 'br',
							),
							array(
								'key' => 'field_6241e29b3df4b',
								'label' => 'Time',
								'name' => 'time',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
					array(
						'key' => 'field_6241f0804978c',
						'label' => 'Total Operation Time',
						'name' => 'total_operation_time',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => 'hours',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6078d4f32d955',
						'label' => 'Pricing',
						'name' => 'pricing',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'sub_fields' => array(
							array(
								'key' => 'field_6078d4fd2d956',
								'label' => 'Margin',
								'name' => 'margin',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '%',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6078d50e2d957',
								'label' => 'EFF',
								'name' => 'eff',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '%',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6078d5242d958',
								'label' => '# People',
								'name' => 'people',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6078d53a2d959',
								'label' => 'EAU',
								'name' => 'eau',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6078d5482d95a',
								'label' => '# of Shift',
								'name' => 'shift',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_61d73807f01de',
								'label' => 'Break In',
								'name' => 'break_in',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '$',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_627aa4b56941c',
								'label' => 'Metal Adder',
								'name' => 'metal_adder',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_6261694ba44cf',
								'label' => 'Unit',
								'name' => 'price_unit',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'ea' => 'per Each',
									'lb' => 'per Lb',
									'k' => 'per K',
									'c' => 'per C',
									'g' => 'per gram',
									'kg' => 'per kilogram',
								),
								'default_value' => 'each',
								'allow_null' => 0,
								'multiple' => 0,
								'ui' => 0,
								'return_format' => 'value',
								'ajax' => 0,
								'placeholder' => '',
							),
						),
					),
					array(
						'key' => 'field_650b340aae037',
						'label' => 'Quantity Breaks',
						'name' => 'quantities',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 0,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Add Break Point',
						'sub_fields' => array(
							array(
								'key' => 'field_650b34148df45',
								'label' => 'Break Point',
								'name' => 'break_point',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
						),
					),
					array(
						'key' => 'field_656f5660bed37',
						'label' => 'Pieces per Load Override',
						'name' => 'pieces_per_load_override',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_65b900b563c88',
						'label' => 'Single Part Weight Override',
						'name' => 'weight_override',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_65b90146de05e',
						'label' => 'Thruput Capacity Override',
						'name' => 'thruput_capacity_override',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_6192c4078782c',
				'label' => 'Raw Specs',
				'name' => 'raw_specs',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6079d6bea491e',
				'label' => 'Quote',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6238c41b168b9',
				'label' => 'Quote #',
				'name' => 'quote_number',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_629f5280b34a1',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'New' => 'New',
					'Pending' => 'Pending',
					'Quoted' => 'Quoted',
					'Canceled' => 'Canceled',
					'No Quote' => 'No Quote',
				),
				'allow_null' => 1,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_62681f0d2493a',
				'label' => 'External ID',
				'name' => 'external_id',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_627959e1168f2',
				'label' => 'Nutshell ID',
				'name' => 'nutshell_id',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_60b6371e58b8f',
				'label' => 'Quantity Breaks',
				'name' => 'quantity_breaks',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Break Point',
				'sub_fields' => array(
					array(
						'key' => 'field_60b6373558b90',
						'label' => 'Break Point',
						'name' => 'break_point',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
			),
			array(
				'key' => 'field_6075ed3ab0f1f',
				'label' => 'Quote Details',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_627aa584e646f',
				'label' => 'Quote Notes',
				'name' => 'quote_notes',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_61f0214d0fa01',
				'label' => 'Quote Pricing Type',
				'name' => 'quote_pricing_type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'special' => 'Special',
					'commodity' => 'Commodity',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'special',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_610ab99f02fe6',
				'label' => 'Quote Date',
				'name' => 'quote_date',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_610ab9b002fe7',
				'label' => 'Follow Up Date',
				'name' => 'follow_up_date',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_610ab9c602fe8',
				'label' => 'Expiration Date',
				'name' => 'expiration_date',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6317660c39641',
				'label' => 'Add Recipient',
				'name' => 'add_recipient',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6317661d39642',
				'label' => 'Recipient(s)',
				'name' => 'recipient',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_630e1153d5f7b',
				'label' => 'No Quote',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_629f5280b34a1',
							'operator' => '==',
							'value' => 'No Quote',
						),
					),
					array(
						array(
							'field' => 'field_629f5280b34a1',
							'operator' => '==',
							'value' => 'Canceled',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_63175e552d3c6',
				'label' => 'Load Template',
				'name' => 'load_template',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Select a template' => 'Select a template',
					'No Quote' => 'No Quote',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_630e1111d5f7a',
				'label' => 'No Quote Email Message',
				'name' => 'no_quote_email_message',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'lead',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

endif;