<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key' => 'group_6241db7e4cb62',
		'title' => 'Process Options',
		'fields' => array(
			array(
				'key' => 'field_6241db7e4f35e',
				'label' => 'Operations',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6241db7e4f39a',
				'label' => 'Operations',
				'name' => 'operations',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_6228e9b0ceac6',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Operation',
				'sub_fields' => array(
					array(
						'key' => 'field_6241db7e59cb9',
						'label' => 'Operation',
						'name' => 'operation',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6241db7e59cf7',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 1,
						'delay' => 0,
					),
					array(
						'key' => 'field_6241db7e59d34',
						'label' => 'Setup Time',
						'name' => 'setup_time',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6241db7e59d70',
						'label' => 'Setup Unit',
						'name' => 'setup_unit',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'S' => 'S',
							'M' => 'M',
							'H' => 'H',
						),
						'allow_null' => 1,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_6241db7e59dac',
						'label' => 'Cycle Time',
						'name' => 'cycle_time',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6241db7e59de9',
						'label' => 'Cycle Unit',
						'name' => 'cycle_unit',
						'type' => 'button_group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'S' => 'S',
							'M' => 'M',
							'H' => 'H',
						),
						'allow_null' => 1,
						'default_value' => '',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_6241db7e59e25',
						'label' => 'Efficiency',
						'name' => 'efficiency',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => 100,
						'placeholder' => '',
						'prepend' => '',
						'append' => '%',
						'min' => 0,
						'max' => 100,
						'step' => '',
					),
					array(
						'key' => 'field_641079a561f69',
						'label' => 'Type',
						'name' => 'type',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'null' => 'Select a type',
							'Prep' => 'Prep',
							'Plating' => 'Plating',
							'Post' => 'Post',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_641079dc61f6a',
						'label' => 'Base Metal',
						'name' => 'base_metal',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_641079a561f69',
									'operator' => '==',
									'value' => 'Prep',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
						),
						'default_value' => array(
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_63e25e6fe9fbe',
						'label' => 'Material',
						'name' => 'material',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => array(
							array(
								array(
									'field' => 'field_641079a561f69',
									'operator' => '==',
									'value' => 'Plating',
								),
							),
						),
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_6660908d75ef7',
				'label' => 'Post Ops Order',
				'name' => 'post_ops_order',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6241db7e4f3d7',
				'label' => 'Recipes',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6241db7e4f413',
				'label' => 'Recipes',
				'name' => 'recipes',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_6279553946c51',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Recipe',
				'sub_fields' => array(
					array(
						'key' => 'field_6279553946c51',
						'label' => 'Base Metal',
						'name' => 'base_metal',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Stainless Steel (300/400 Series)' => 'Stainless Steel (300/400 Series)',
							'ABS (PLASTIC)' => 'ABS (PLASTIC)',
							'ABS/PC (PLASTIC)' => 'ABS/PC (PLASTIC)',
							'ALBEMET' => 'ALBEMET',
							'Aluminum-Silicon (AlSi10Mg)' => 'Aluminum-Silicon (AlSi10Mg)',
							'Alumina (Ceramic)' => 'Alumina (Ceramic)',
							'Aluminum Alloys (1000, 3000, 4000, 5000,,6000)' => 'Aluminum Alloys (1000, 3000, 4000, 5000,,6000)',
							'Aluminum Alloys (2000, 7000)' => 'Aluminum Alloys (2000, 7000)',
							'Aluminum (Cast)' => 'Aluminum (Cast)',
							'Alloy 41 (NiCrCoMo)' => 'Alloy 41 (NiCrCoMo)',
							'Alloy 52 (NiFe)' => 'Alloy 52 (NiFe)',
							'Beryllium-Copper' => 'Beryllium-Copper',
							'Borosilicate Glass' => 'Borosilicate Glass',
							'Brass/Bronze' => 'Brass/Bronze',
							'Brass/Bronze (Leaded)' => 'Brass/Bronze (Leaded)',
							'Carbon/Graphite-Epoxy Composite' => 'Carbon/Graphite-Epoxy Composite',
							'Copper' => 'Copper',
							'Copper-Molybdenum 25/75' => 'Copper-Molybdenum 25/75',
							'Copper-Tungsten 25/75' => 'Copper-Tungsten 25/75',
							'FEP (PLASTIC)' => 'FEP (PLASTIC)',
							'INVAR-36 (NICKEL-IRON ALLOY)' => 'INVAR-36 (NICKEL-IRON ALLOY)',
							'Carbon & Low Alloy Steel' => 'Carbon & Low Alloy Steel',
							'Powdered Metal (Steel)' => 'Powdered Metal (Steel)',
							'Steel (Leaded)' => 'Steel (Leaded)',
							'Alloy Steel (Cr > 1.5%)' => 'Alloy Steel (Cr > 1.5%)',
							'Kovar (NI-CO-FE ALLOY)' => 'Kovar (NI-CO-FE ALLOY)',
							'L605 Co-Cr-W-Ni Alloy' => 'L605 Co-Cr-W-Ni Alloy',
							'Lead' => 'Lead',
							'Liquid Crystal Polymer (LCP) 30% GLASS FILLED' => 'Liquid Crystal Polymer (LCP) 30% GLASS FILLED',
							'Magnesium Alloys' => 'Magnesium Alloys',
							'Magnesium Silicate (Forsterite: Mg2SiO4)' => 'Magnesium Silicate (Forsterite: Mg2SiO4)',
							'Molybdenum' => 'Molybdenum',
							'Monel (NICKEL-COPPER ALLOY)' => 'Monel (NICKEL-COPPER ALLOY)',
							'Neodymium' => 'Neodymium',
							'Nichrome 80 (ALLOY 650)' => 'Nichrome 80 (ALLOY 650)',
							'Nickel' => 'Nickel',
							'Niobium' => 'Niobium',
							'Nylon (Polyamide)' => 'Nylon (Polyamide)',
							'Nylon (Polyamide Glass-Filled)' => 'Nylon (Polyamide Glass-Filled)',
							'Polyacetal (POM)' => 'Polyacetal (POM)',
							'Polybutylene Terephthalate (PBT)' => 'Polybutylene Terephthalate (PBT)',
							'Polybenzimidazole (PBI)' => 'Polybenzimidazole (PBI)',
							'Polycarbonate' => 'Polycarbonate',
							'Palladium' => 'Palladium',
							'Polyether Ether Ketone (PEEK)' => 'Polyether Ether Ketone (PEEK)',
							'Polyetherimide (PEI-Ultem)' => 'Polyetherimide (PEI-Ultem)',
							'Poly(methyl methacrylate) PMMA' => 'Poly(methyl methacrylate) PMMA',
							'Polymethylpentene (PMP, aka TPX)' => 'Polymethylpentene (PMP, aka TPX)',
							'Polyphenylene Sulfide (Ryton R4 - 40% Fiberglass Filled)' => 'Polyphenylene Sulfide (Ryton R4 - 40% Fiberglass Filled)',
							'Polypropylene (PP)' => 'Polypropylene (PP)',
							'Polystyrene (PS)' => 'Polystyrene (PS)',
							'Polyvinyl Chloride (PVC)' => 'Polyvinyl Chloride (PVC)',
							'Platinum' => 'Platinum',
							'PZT-CERAMIC' => 'PZT-CERAMIC',
							'Silver' => 'Silver',
							'Silicon' => 'Silicon',
							'Silicon-Carbide' => 'Silicon-Carbide',
							'Tin' => 'Tin',
							'Titanium (Commercially Pure)' => 'Titanium (Commercially Pure)',
							'Titanium (Alloy)' => 'Titanium (Alloy)',
							'Tungsten' => 'Tungsten',
							'TZM Molybdenum' => 'TZM Molybdenum',
							'Zinc-Diecast' => 'Zinc-Diecast',
							'VIBRATORY BOWL FINISH' => 'VIBRATORY BOWL FINISH',
							'Urethane-Acrylate Blends' => 'Urethane-Acrylate Blends',
							'Vermiculite' => 'Vermiculite',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e60fbd',
						'label' => 'Process 1',
						'name' => 'process_1',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'None' => 'None',
							'BAKING' => 'BAKING',
							'BLAST (AL OXIDE)' => 'BLAST (AL OXIDE)',
							'BLAST (GLASS BEAD)' => 'BLAST (GLASS BEAD)',
							'TUMBLE BLASTING (STEEL SHOT)' => 'TUMBLE BLASTING (STEEL SHOT)',
							'CHEM FILM' => 'CHEM FILM',
							'COPPER (ALKALINE)' => 'COPPER (ALKALINE)',
							'COPPER-BARREL (ALKALINE)' => 'COPPER-BARREL (ALKALINE)',
							'COPPER-BARREL (ACID)' => 'COPPER-BARREL (ACID)',
							'COPPER-BARREL (NEUTRAL)' => 'COPPER-BARREL (NEUTRAL)',
							'COPPER-RACK (ACID)' => 'COPPER-RACK (ACID)',
							'COPPER-RACK (NEUTRAL)' => 'COPPER-RACK (NEUTRAL)',
							'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
							'ELECTROLESS NICKEL (< 1% B)' => 'ELECTROLESS NICKEL (< 1% B)',
							'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
							'ELECTROLESS NICKEL (11-13% P)' => 'ELECTROLESS NICKEL (11-13% P)',
							'ELECTROLESS NICKEL (1-4% P)' => 'ELECTROLESS NICKEL (1-4% P)',
							'ELECTROLESS NICKEL (5-9% P)' => 'ELECTROLESS NICKEL (5-9% P)',
							'GOLD-BARREL (99.0% + AU; HKN 200+)' => 'GOLD-BARREL (99.0% + AU; HKN 200+)',
							'GOLD-BARREL (99.7% + AU; HKN 130-200)' => 'GOLD-BARREL (99.7% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 130-200)' => 'GOLD-BARREL (99.9% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 90 MAX)' => 'GOLD-BARREL (99.9% + AU; HKN 90 MAX)',
							'GOLD-BARREL (99.9% + AU; HKN 91-129)' => 'GOLD-BARREL (99.9% + AU; HKN 91-129)',
							'GOLD-RACK (99.0% + AU; HKN 200+)' => 'GOLD-RACK (99.0% + AU; HKN 200+)',
							'GOLD-RACK (99.7% + AU; HKN 130-200)' => 'GOLD-RACK (99.7% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 130-200)' => 'GOLD-RACK (99.9% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 90 MAX)' => 'GOLD-RACK (99.9% + AU; HKN 90 MAX)',
							'GOLD-RACK (99.9% + AU; HKN 91-129)' => 'GOLD-RACK (99.9% + AU; HKN 91-129)',
							'IMMERSION GOLD' => 'IMMERSION GOLD',
							'MASKING' => 'MASKING',
							'NICKEL-WOODS STRIKE (BARREL)' => 'NICKEL-WOODS STRIKE (BARREL)',
							'NICKEL-WOODS STRIKE (RACK)' => 'NICKEL-WOODS STRIKE (RACK)',
							'NICKEL-SULFAMATE (BARREL)' => 'NICKEL-SULFAMATE (BARREL)',
							'NICKEL-SULFAMATE (RACK)' => 'NICKEL-SULFAMATE (RACK)',
							'PALLADIUM (BARREL)' => 'PALLADIUM (BARREL)',
							'PALLADIUM-NICKEL-BARREL (80PD-20NI)' => 'PALLADIUM-NICKEL-BARREL (80PD-20NI)',
							'PALLADIUM-NICKEL-RACK (80PD-20NI)' => 'PALLADIUM-NICKEL-RACK (80PD-20NI)',
							'PALLADIUM (RACK)' => 'PALLADIUM (RACK)',
							'PLATINUM (BARREL)' => 'PLATINUM (BARREL)',
							'PLATINUM (RACK)' => 'PLATINUM (RACK)',
							'RHODIUM (BARREL)' => 'RHODIUM (BARREL)',
							'RHODIUM (RACK)' => 'RHODIUM (RACK)',
							'RUTHENIUM (BARREL)' => 'RUTHENIUM (BARREL)',
							'RUTHENIUM (RACK)' => 'RUTHENIUM (RACK)',
							'SILVER-BARREL (BRIGHT)' => 'SILVER-BARREL (BRIGHT)',
							'SILVER-BARREL (MATTE)' => 'SILVER-BARREL (MATTE)',
							'SILVER-BARREL (SEMI-BRIGHT)' => 'SILVER-BARREL (SEMI-BRIGHT)',
							'SILVER-RACK (BRIGHT)' => 'SILVER-RACK (BRIGHT)',
							'SILVER-RACK (MATTE)' => 'SILVER-RACK (MATTE)',
							'SILVER-RACK (SEMI-BRIGHT)' => 'SILVER-RACK (SEMI-BRIGHT)',
							'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)' => 'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)',
							'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)' => 'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)',
							'TIN (IMMERSION)' => 'TIN (IMMERSION)',
							'TIN-BARREL (MATTE)' => 'TIN-BARREL (MATTE)',
							'TIN-RACK (BRIGHT)' => 'TIN-RACK (BRIGHT)',
							'TIN-BARREL (BRIGHT)' => 'TIN-BARREL (BRIGHT)',
							'TIN-RACK (MATTE)' => 'TIN-RACK (MATTE)',
							'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)',
							'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)',
							'VIBRATORY FINISH' => 'VIBRATORY FINISH',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e60ffb',
						'label' => 'Process 2',
						'name' => 'process_2',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'None' => 'None',
							'BAKING' => 'BAKING',
							'BLAST (AL OXIDE)' => 'BLAST (AL OXIDE)',
							'BLAST (GLASS BEAD)' => 'BLAST (GLASS BEAD)',
							'TUMBLE BLASTING (STEEL SHOT)' => 'TUMBLE BLASTING (STEEL SHOT)',
							'CHEM FILM' => 'CHEM FILM',
							'COPPER (ALKALINE)' => 'COPPER (ALKALINE)',
							'COPPER-BARREL (ALKALINE)' => 'COPPER-BARREL (ALKALINE)',
							'COPPER-BARREL (ACID)' => 'COPPER-BARREL (ACID)',
							'COPPER-BARREL (NEUTRAL)' => 'COPPER-BARREL (NEUTRAL)',
							'COPPER-RACK (ACID)' => 'COPPER-RACK (ACID)',
							'COPPER-RACK (NEUTRAL)' => 'COPPER-RACK (NEUTRAL)',
							'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
							'ELECTROLESS NICKEL (< 1% B)' => 'ELECTROLESS NICKEL (< 1% B)',
							'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
							'ELECTROLESS NICKEL (11-13% P)' => 'ELECTROLESS NICKEL (11-13% P)',
							'ELECTROLESS NICKEL (1-4% P)' => 'ELECTROLESS NICKEL (1-4% P)',
							'ELECTROLESS NICKEL (5-9% P)' => 'ELECTROLESS NICKEL (5-9% P)',
							'GOLD-BARREL (99.0% + AU; HKN 200+)' => 'GOLD-BARREL (99.0% + AU; HKN 200+)',
							'GOLD-BARREL (99.7% + AU; HKN 130-200)' => 'GOLD-BARREL (99.7% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 130-200)' => 'GOLD-BARREL (99.9% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 90 MAX)' => 'GOLD-BARREL (99.9% + AU; HKN 90 MAX)',
							'GOLD-BARREL (99.9% + AU; HKN 91-129)' => 'GOLD-BARREL (99.9% + AU; HKN 91-129)',
							'GOLD-RACK (99.0% + AU; HKN 200+)' => 'GOLD-RACK (99.0% + AU; HKN 200+)',
							'GOLD-RACK (99.7% + AU; HKN 130-200)' => 'GOLD-RACK (99.7% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 130-200)' => 'GOLD-RACK (99.9% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 90 MAX)' => 'GOLD-RACK (99.9% + AU; HKN 90 MAX)',
							'GOLD-RACK (99.9% + AU; HKN 91-129)' => 'GOLD-RACK (99.9% + AU; HKN 91-129)',
							'IMMERSION GOLD' => 'IMMERSION GOLD',
							'MASKING' => 'MASKING',
							'NICKEL-WOODS STRIKE (BARREL)' => 'NICKEL-WOODS STRIKE (BARREL)',
							'NICKEL-WOODS STRIKE (RACK)' => 'NICKEL-WOODS STRIKE (RACK)',
							'NICKEL-SULFAMATE (BARREL)' => 'NICKEL-SULFAMATE (BARREL)',
							'NICKEL-SULFAMATE (RACK)' => 'NICKEL-SULFAMATE (RACK)',
							'PALLADIUM (BARREL)' => 'PALLADIUM (BARREL)',
							'PALLADIUM-NICKEL-BARREL (80PD-20NI)' => 'PALLADIUM-NICKEL-BARREL (80PD-20NI)',
							'PALLADIUM-NICKEL-RACK (80PD-20NI)' => 'PALLADIUM-NICKEL-RACK (80PD-20NI)',
							'PALLADIUM (RACK)' => 'PALLADIUM (RACK)',
							'PLATINUM (BARREL)' => 'PLATINUM (BARREL)',
							'PLATINUM (RACK)' => 'PLATINUM (RACK)',
							'RHODIUM (BARREL)' => 'RHODIUM (BARREL)',
							'RHODIUM (RACK)' => 'RHODIUM (RACK)',
							'RUTHENIUM (BARREL)' => 'RUTHENIUM (BARREL)',
							'RUTHENIUM (RACK)' => 'RUTHENIUM (RACK)',
							'SILVER-BARREL (BRIGHT)' => 'SILVER-BARREL (BRIGHT)',
							'SILVER-BARREL (MATTE)' => 'SILVER-BARREL (MATTE)',
							'SILVER-BARREL (SEMI-BRIGHT)' => 'SILVER-BARREL (SEMI-BRIGHT)',
							'SILVER-RACK (BRIGHT)' => 'SILVER-RACK (BRIGHT)',
							'SILVER-RACK (MATTE)' => 'SILVER-RACK (MATTE)',
							'SILVER-RACK (SEMI-BRIGHT)' => 'SILVER-RACK (SEMI-BRIGHT)',
							'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)' => 'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)',
							'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)' => 'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)',
							'TIN (IMMERSION)' => 'TIN (IMMERSION)',
							'TIN-BARREL (MATTE)' => 'TIN-BARREL (MATTE)',
							'TIN-RACK (BRIGHT)' => 'TIN-RACK (BRIGHT)',
							'TIN-BARREL (BRIGHT)' => 'TIN-BARREL (BRIGHT)',
							'TIN-RACK (MATTE)' => 'TIN-RACK (MATTE)',
							'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)',
							'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)',
							'VIBRATORY FINISH' => 'VIBRATORY FINISH',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e61037',
						'label' => 'Process 3',
						'name' => 'process_3',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'None' => 'None',
							'BAKING' => 'BAKING',
							'BLAST (AL OXIDE)' => 'BLAST (AL OXIDE)',
							'BLAST (GLASS BEAD)' => 'BLAST (GLASS BEAD)',
							'TUMBLE BLASTING (STEEL SHOT)' => 'TUMBLE BLASTING (STEEL SHOT)',
							'CHEM FILM' => 'CHEM FILM',
							'COPPER (ALKALINE)' => 'COPPER (ALKALINE)',
							'COPPER-BARREL (ALKALINE)' => 'COPPER-BARREL (ALKALINE)',
							'COPPER-BARREL (ACID)' => 'COPPER-BARREL (ACID)',
							'COPPER-BARREL (NEUTRAL)' => 'COPPER-BARREL (NEUTRAL)',
							'COPPER-RACK (ACID)' => 'COPPER-RACK (ACID)',
							'COPPER-RACK (NEUTRAL)' => 'COPPER-RACK (NEUTRAL)',
							'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
							'ELECTROLESS NICKEL (< 1% B)' => 'ELECTROLESS NICKEL (< 1% B)',
							'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
							'ELECTROLESS NICKEL (11-13% P)' => 'ELECTROLESS NICKEL (11-13% P)',
							'ELECTROLESS NICKEL (1-4% P)' => 'ELECTROLESS NICKEL (1-4% P)',
							'ELECTROLESS NICKEL (5-9% P)' => 'ELECTROLESS NICKEL (5-9% P)',
							'GOLD-BARREL (99.0% + AU; HKN 200+)' => 'GOLD-BARREL (99.0% + AU; HKN 200+)',
							'GOLD-BARREL (99.7% + AU; HKN 130-200)' => 'GOLD-BARREL (99.7% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 130-200)' => 'GOLD-BARREL (99.9% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 90 MAX)' => 'GOLD-BARREL (99.9% + AU; HKN 90 MAX)',
							'GOLD-BARREL (99.9% + AU; HKN 91-129)' => 'GOLD-BARREL (99.9% + AU; HKN 91-129)',
							'GOLD-RACK (99.0% + AU; HKN 200+)' => 'GOLD-RACK (99.0% + AU; HKN 200+)',
							'GOLD-RACK (99.7% + AU; HKN 130-200)' => 'GOLD-RACK (99.7% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 130-200)' => 'GOLD-RACK (99.9% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 90 MAX)' => 'GOLD-RACK (99.9% + AU; HKN 90 MAX)',
							'GOLD-RACK (99.9% + AU; HKN 91-129)' => 'GOLD-RACK (99.9% + AU; HKN 91-129)',
							'IMMERSION GOLD' => 'IMMERSION GOLD',
							'MASKING' => 'MASKING',
							'NICKEL-WOODS STRIKE (BARREL)' => 'NICKEL-WOODS STRIKE (BARREL)',
							'NICKEL-WOODS STRIKE (RACK)' => 'NICKEL-WOODS STRIKE (RACK)',
							'NICKEL-SULFAMATE (BARREL)' => 'NICKEL-SULFAMATE (BARREL)',
							'NICKEL-SULFAMATE (RACK)' => 'NICKEL-SULFAMATE (RACK)',
							'PALLADIUM (BARREL)' => 'PALLADIUM (BARREL)',
							'PALLADIUM-NICKEL-BARREL (80PD-20NI)' => 'PALLADIUM-NICKEL-BARREL (80PD-20NI)',
							'PALLADIUM-NICKEL-RACK (80PD-20NI)' => 'PALLADIUM-NICKEL-RACK (80PD-20NI)',
							'PALLADIUM (RACK)' => 'PALLADIUM (RACK)',
							'PLATINUM (BARREL)' => 'PLATINUM (BARREL)',
							'PLATINUM (RACK)' => 'PLATINUM (RACK)',
							'RHODIUM (BARREL)' => 'RHODIUM (BARREL)',
							'RHODIUM (RACK)' => 'RHODIUM (RACK)',
							'RUTHENIUM (BARREL)' => 'RUTHENIUM (BARREL)',
							'RUTHENIUM (RACK)' => 'RUTHENIUM (RACK)',
							'SILVER-BARREL (BRIGHT)' => 'SILVER-BARREL (BRIGHT)',
							'SILVER-BARREL (MATTE)' => 'SILVER-BARREL (MATTE)',
							'SILVER-BARREL (SEMI-BRIGHT)' => 'SILVER-BARREL (SEMI-BRIGHT)',
							'SILVER-RACK (BRIGHT)' => 'SILVER-RACK (BRIGHT)',
							'SILVER-RACK (MATTE)' => 'SILVER-RACK (MATTE)',
							'SILVER-RACK (SEMI-BRIGHT)' => 'SILVER-RACK (SEMI-BRIGHT)',
							'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)' => 'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)',
							'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)' => 'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)',
							'TIN (IMMERSION)' => 'TIN (IMMERSION)',
							'TIN-BARREL (MATTE)' => 'TIN-BARREL (MATTE)',
							'TIN-RACK (BRIGHT)' => 'TIN-RACK (BRIGHT)',
							'TIN-BARREL (BRIGHT)' => 'TIN-BARREL (BRIGHT)',
							'TIN-RACK (MATTE)' => 'TIN-RACK (MATTE)',
							'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)',
							'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)',
							'VIBRATORY FINISH' => 'VIBRATORY FINISH',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e61073',
						'label' => 'Process 4',
						'name' => 'process_4',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'None' => 'None',
							'BAKING' => 'BAKING',
							'BLAST (AL OXIDE)' => 'BLAST (AL OXIDE)',
							'BLAST (GLASS BEAD)' => 'BLAST (GLASS BEAD)',
							'TUMBLE BLASTING (STEEL SHOT)' => 'TUMBLE BLASTING (STEEL SHOT)',
							'CHEM FILM' => 'CHEM FILM',
							'COPPER (ALKALINE)' => 'COPPER (ALKALINE)',
							'COPPER-BARREL (ALKALINE)' => 'COPPER-BARREL (ALKALINE)',
							'COPPER-BARREL (ACID)' => 'COPPER-BARREL (ACID)',
							'COPPER-BARREL (NEUTRAL)' => 'COPPER-BARREL (NEUTRAL)',
							'COPPER-RACK (ACID)' => 'COPPER-RACK (ACID)',
							'COPPER-RACK (NEUTRAL)' => 'COPPER-RACK (NEUTRAL)',
							'ELECTROLESS COPPER' => 'ELECTROLESS COPPER',
							'ELECTROLESS NICKEL (< 1% B)' => 'ELECTROLESS NICKEL (< 1% B)',
							'ELECTROLESS PALLADIUM' => 'ELECTROLESS PALLADIUM',
							'ELECTROLESS NICKEL (11-13% P)' => 'ELECTROLESS NICKEL (11-13% P)',
							'ELECTROLESS NICKEL (1-4% P)' => 'ELECTROLESS NICKEL (1-4% P)',
							'ELECTROLESS NICKEL (5-9% P)' => 'ELECTROLESS NICKEL (5-9% P)',
							'GOLD-BARREL (99.0% + AU; HKN 200+)' => 'GOLD-BARREL (99.0% + AU; HKN 200+)',
							'GOLD-BARREL (99.7% + AU; HKN 130-200)' => 'GOLD-BARREL (99.7% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 130-200)' => 'GOLD-BARREL (99.9% + AU; HKN 130-200)',
							'GOLD-BARREL (99.9% + AU; HKN 90 MAX)' => 'GOLD-BARREL (99.9% + AU; HKN 90 MAX)',
							'GOLD-BARREL (99.9% + AU; HKN 91-129)' => 'GOLD-BARREL (99.9% + AU; HKN 91-129)',
							'GOLD-RACK (99.0% + AU; HKN 200+)' => 'GOLD-RACK (99.0% + AU; HKN 200+)',
							'GOLD-RACK (99.7% + AU; HKN 130-200)' => 'GOLD-RACK (99.7% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 130-200)' => 'GOLD-RACK (99.9% + AU; HKN 130-200)',
							'GOLD-RACK (99.9% + AU; HKN 90 MAX)' => 'GOLD-RACK (99.9% + AU; HKN 90 MAX)',
							'GOLD-RACK (99.9% + AU; HKN 91-129)' => 'GOLD-RACK (99.9% + AU; HKN 91-129)',
							'IMMERSION GOLD' => 'IMMERSION GOLD',
							'MASKING' => 'MASKING',
							'NICKEL-WOODS STRIKE (BARREL)' => 'NICKEL-WOODS STRIKE (BARREL)',
							'NICKEL-WOODS STRIKE (RACK)' => 'NICKEL-WOODS STRIKE (RACK)',
							'NICKEL-SULFAMATE (BARREL)' => 'NICKEL-SULFAMATE (BARREL)',
							'NICKEL-SULFAMATE (RACK)' => 'NICKEL-SULFAMATE (RACK)',
							'PALLADIUM (BARREL)' => 'PALLADIUM (BARREL)',
							'PALLADIUM-NICKEL-BARREL (80PD-20NI)' => 'PALLADIUM-NICKEL-BARREL (80PD-20NI)',
							'PALLADIUM-NICKEL-RACK (80PD-20NI)' => 'PALLADIUM-NICKEL-RACK (80PD-20NI)',
							'PALLADIUM (RACK)' => 'PALLADIUM (RACK)',
							'PLATINUM (BARREL)' => 'PLATINUM (BARREL)',
							'PLATINUM (RACK)' => 'PLATINUM (RACK)',
							'RHODIUM (BARREL)' => 'RHODIUM (BARREL)',
							'RHODIUM (RACK)' => 'RHODIUM (RACK)',
							'RUTHENIUM (BARREL)' => 'RUTHENIUM (BARREL)',
							'RUTHENIUM (RACK)' => 'RUTHENIUM (RACK)',
							'SILVER-BARREL (BRIGHT)' => 'SILVER-BARREL (BRIGHT)',
							'SILVER-BARREL (MATTE)' => 'SILVER-BARREL (MATTE)',
							'SILVER-BARREL (SEMI-BRIGHT)' => 'SILVER-BARREL (SEMI-BRIGHT)',
							'SILVER-RACK (BRIGHT)' => 'SILVER-RACK (BRIGHT)',
							'SILVER-RACK (MATTE)' => 'SILVER-RACK (MATTE)',
							'SILVER-RACK (SEMI-BRIGHT)' => 'SILVER-RACK (SEMI-BRIGHT)',
							'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)' => 'SILVER ANODIC-ANTI-TARNISH (RACK ONLY)',
							'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)' => 'SILVER IMMERSION-ANTI-TARNISH (BARREL ONLY)',
							'TIN (IMMERSION)' => 'TIN (IMMERSION)',
							'TIN-BARREL (MATTE)' => 'TIN-BARREL (MATTE)',
							'TIN-RACK (BRIGHT)' => 'TIN-RACK (BRIGHT)',
							'TIN-BARREL (BRIGHT)' => 'TIN-BARREL (BRIGHT)',
							'TIN-RACK (MATTE)' => 'TIN-RACK (MATTE)',
							'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (SINGLE CYCLE)',
							'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)' => 'RESIN VACUUM IMPREGNATION (DOUBLE CYCLE)',
							'VIBRATORY FINISH' => 'VIBRATORY FINISH',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e610af',
						'label' => 'Plating Line',
						'name' => 'plating_line',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'5 GALLON TANK' => '5 GALLON TANK',
							'2 X 5 GALLON TANK ' => '2 X 5 GALLON TANK ',
							'3 X 5 GALLON TANK' => '3 X 5 GALLON TANK',
							'4 X 5 GALLON TANK' => '4 X 5 GALLON TANK',
							'2.5 GALLON BEAKER' => '2.5 GALLON BEAKER',
							'2X 2.5 GALLON BEAKER' => '2X 2.5 GALLON BEAKER',
							'LAB' => 'LAB',
							'LARGE VIBE BOWL' => 'LARGE VIBE BOWL',
							'LINE 10 BR TIN' => 'LINE 10 BR TIN',
							'LINE 15 MINI HL' => 'LINE 15 MINI HL',
							'LINE 15 MINI HL TIN' => 'LINE 15 MINI HL TIN',
							'LINE 15 MINI HL ZN' => 'LINE 15 MINI HL ZN',
							'LINE 15 MINI HL ZN-NI' => 'LINE 15 MINI HL ZN-NI',
							'LINE 17 EN 1X' => 'LINE 17 EN 1X',
							'LINE 17 EN 2X' => 'LINE 17 EN 2X',
							'LINE 17 EN 3X' => 'LINE 17 EN 3X',
							'LINE 2 ZINC' => 'LINE 2 ZINC',
							'ULTRASONIC WASHER' => 'ULTRASONIC WASHER',
							'VACUUM IMPREG' => 'VACUUM IMPREG',
							'ID TUBE' => 'ID TUBE',
							'TI-PT LINE' => 'TI-PT LINE',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e610f4',
						'label' => 'Plating Method',
						'name' => 'plating_method',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'Barrel' => 'Barrel',
							'Rack' => 'Rack',
						),
						'default_value' => false,
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'field_6241db7e61131',
						'label' => 'Plating Tool',
						'name' => 'plating_tool',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33.3333',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'39"' => '39"',
							'B' => 'B',
							'Jewelers' => 'Jewelers',
							'Micro' => 'Micro',
							'Micro-8512' => 'Micro-8512',
							'S PPB 44' => 'S PPB 44',
							'S PBB 66' => 'S PBB 66',
							'Tandem B' => 'Tandem B',
							'V100 90MM' => 'V100 90MM',
							'10 CU.FT. BASKET' => '10 CU.FT. BASKET',
							'CHEM FILM' => 'CHEM FILM',
							'EN TANK SPECIAL' => 'EN TANK SPECIAL',
							'Flat Large Hook' => 'Flat Large Hook',
							'Ideal Rack' => 'Ideal Rack',
							'Ideal Rack Double Sided' => 'Ideal Rack Double Sided',
							'LAB WIRE' => 'LAB WIRE',
							'Large Pincher Tine' => 'Large Pincher Tine',
							'Medico Bullet' => 'Medico Bullet',
							'Mini Pincher Tine' => 'Mini Pincher Tine',
							'Pin Rack' => 'Pin Rack',
							'S&Z Rack' => 'S&Z Rack',
							'Small U-Hook' => 'Small U-Hook',
							'SS Flat Tipped Pincher Tine' => 'SS Flat Tipped Pincher Tine',
							'Stick Pincher Tine' => 'Stick Pincher Tine',
							'THERMOCOUPLE RACK' => 'THERMOCOUPLE RACK',
							'ID TUBE PLATING' => 'ID TUBE PLATING',
							'ULTRASONIC WASH TRAY' => 'ULTRASONIC WASH TRAY',
							'PT PLATING LINE RACK' => 'PT PLATING LINE RACK',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-process-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

endif;		