<?php

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key' => 'group_6241dc1018976',
		'title' => 'Quote Options',
		'fields' => array(
			array(
				'key' => 'field_6241dc101a740',
				'label' => 'Quotes',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6241dc101a77a',
				'label' => 'Quote Header',
				'name' => 'quote_header',
				'type' => 'wysiwyg',
				'instructions' => 'first page only',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6241dc101a7b4',
				'label' => 'Quote Footer',
				'name' => 'quote_footer',
				'type' => 'wysiwyg',
				'instructions' => 'last page only (before terms)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6241dc101a7ee',
				'label' => 'Quote Terms',
				'name' => 'quote_terms',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_681cf2f000001',
				'label' => 'PDFs',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_681cf2f000002',
				'label' => 'Quote Form ID',
				'name' => 'quote_form_id',
				'type' => 'number',
				'instructions' => 'Leave blank to detect the Gravity Form automatically from your existing quote PDFs or entries.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => '',
				'step' => 1,
			),
			array(
				'key' => 'field_681cf2f000003',
				'label' => 'Quote PDF ID',
				'name' => 'quote_pdf_id',
				'type' => 'text',
				'instructions' => 'Leave blank to detect the Gravity PDF named "Quote PDF" on your configured form.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_681cf2f000004',
				'label' => 'Routing PDF ID',
				'name' => 'routing_pdf_id',
				'type' => 'text',
				'instructions' => 'Leave blank to detect the Gravity PDF named "Routing PDF" on your configured form.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_681cf2f000005',
				'label' => 'Quote PDF Layout',
				'name' => 'quote_pdf_layout',
				'type' => 'select',
				'instructions' => 'Choose how quote PDFs should be styled when they are generated from this workspace.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '12.5',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'standard' => 'Standard',
					'compact' => 'Compact',
				),
				'default_value' => 'standard',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_681cf2f000006',
				'label' => 'Routing PDF Layout',
				'name' => 'routing_pdf_layout',
				'type' => 'select',
				'instructions' => 'Choose how routing PDFs should be styled when they are generated from this workspace.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '12.5',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'standard' => 'Standard',
					'compact' => 'Compact',
				),
				'default_value' => 'standard',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_63175da8b53b1',
				'label' => 'Emails',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_63175db0b53b2',
				'label' => 'Email Templates',
				'name' => 'email_templates',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_63175dc5b53b3',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Add Template',
				'sub_fields' => array(
					array(
						'key' => 'field_63175dc5b53b3',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '30',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_63175dcdb53b4',
						'label' => 'Template',
						'name' => 'template',
						'type' => 'wysiwyg',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '70',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'full',
						'media_upload' => 0,
						'delay' => 1,
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-quote-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	) );

endif;		
